tps-alert-threshold: 15
required-plugins:
  ChestShop: false
  Citizens: false
  CommandHelper: true
  CoreProtect: false
  CVBasicNBT: false
  CVBlocks: false
  CVChat: true
  CVClaims: false
  CVCreativeItemControl: false
  CVCreativePlots: false
  CVElytraCraft: false
  CVFarmlands: false
  CVFlags: false
  CVHat: false
  CVHeadAnim: false
  CVHome: false
  CVIPC: true
  CVLiftSigns: false
  CVLoadouts: false
  CVLocation: false
  CVMenu: false
  CVMiningNotifier: false
  CVMobCap: false
  CVNetherPortalBlocker: false
  CVOptionMenu: false
  CVPlayerSpleefUtil: false
  CVPortal: true
  CVRanks: false
  CVReturn: false
  CVTools: true
  CVVanish: true
  CVWorldEdit: false
  Denizen: false
  DiscordSender: true
  FastAsyncWorldEdit: false
  HeadDatabase: false
  LibsDisguises: false
  Luckperms: true
  LWCX: false
  Multiverse-Core: true
  NullTerrain: false
  OpenInv: false
  Orebfuscator: false
  PlaceholderAPI: true
  ProtocolLib: true
  SaferWater: false
  Sentinel: false
  Spark: true
  SystemChat: true
  Vault: false
  ViaVersion: false
  VoxelSniper: false
  WorldEdit: false
  Worldguard: true